/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.view;

/**
 *
 * @author rafae
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        javax.swing.UIManager.put("OptionPane.yesButtonText", "Sim");
        javax.swing.UIManager.put("OptionPane.noButtonText", "Não");
        javax.swing.UIManager.put("OptionPane.cancelButtonText", "Cancelar");
        javax.swing.UIManager.put("OptionPane.okButtonText", "OK");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbMenu = new javax.swing.JMenuBar();
        mRegister = new javax.swing.JMenu();
        mIWorkshopRegister = new javax.swing.JMenuItem();
        mIVehicleRegister = new javax.swing.JMenuItem();
        mIServiceRegister = new javax.swing.JMenuItem();
        mISchedulingRegister = new javax.swing.JMenuItem();
        mConsult = new javax.swing.JMenu();
        mIWorkshopConsult = new javax.swing.JMenuItem();
        mIVehicleConsult = new javax.swing.JMenuItem();
        mIServiceConsult = new javax.swing.JMenuItem();
        mISchedulingConsult = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Agendamento - Oficina");

        mRegister.setText("Cadastrar");

        mIWorkshopRegister.setText("Oficina");
        mIWorkshopRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIWorkshopRegisterActionPerformed(evt);
            }
        });
        mRegister.add(mIWorkshopRegister);

        mIVehicleRegister.setText("Veículo");
        mIVehicleRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIVehicleRegisterActionPerformed(evt);
            }
        });
        mRegister.add(mIVehicleRegister);

        mIServiceRegister.setText("Serviço");
        mRegister.add(mIServiceRegister);

        mISchedulingRegister.setText("Agendamento");
        mRegister.add(mISchedulingRegister);

        mbMenu.add(mRegister);

        mConsult.setText("Consultar");

        mIWorkshopConsult.setText("Oficinas");
        mConsult.add(mIWorkshopConsult);

        mIVehicleConsult.setText("Veículos");
        mConsult.add(mIVehicleConsult);

        mIServiceConsult.setText("Serviços");
        mIServiceConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIServiceConsultActionPerformed(evt);
            }
        });
        mConsult.add(mIServiceConsult);

        mISchedulingConsult.setText("Agendamentos");
        mConsult.add(mISchedulingConsult);

        mbMenu.add(mConsult);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mIVehicleRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIVehicleRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mIVehicleRegisterActionPerformed

    private void mIServiceConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIServiceConsultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mIServiceConsultActionPerformed

    private void mIWorkshopRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIWorkshopRegisterActionPerformed
        // TODO add your handling code here:

        RegisterWorkshop rwdlg = new RegisterWorkshop(this, true);
        rwdlg.setVisible(true);


    }//GEN-LAST:event_mIWorkshopRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mConsult;
    private javax.swing.JMenuItem mISchedulingConsult;
    private javax.swing.JMenuItem mISchedulingRegister;
    private javax.swing.JMenuItem mIServiceConsult;
    private javax.swing.JMenuItem mIServiceRegister;
    private javax.swing.JMenuItem mIVehicleConsult;
    private javax.swing.JMenuItem mIVehicleRegister;
    private javax.swing.JMenuItem mIWorkshopConsult;
    private javax.swing.JMenuItem mIWorkshopRegister;
    private javax.swing.JMenu mRegister;
    private javax.swing.JMenuBar mbMenu;
    // End of variables declaration//GEN-END:variables
}
